### ISSUE TITLE
LFS configuration

### ISSUE THREAD

**Issue by hamedjalali1982** [nfdi4plants/arcmanager_backend#4]
Two cases related to the configuration of the LFS in the backend phase:

- To use LFS for large data files, we need to use this command in the CLI: `git lfs track "*.file_extension"`, which defines the file extensions. In particular, if there are multiple data types in a test folder, we need to repeat this command for all file extensions in the command line. 

- In addition, Gitlab issues the warning "Large file" for a file size of  `=> 4 GB` and returns an error after executing the push command. The problem can be solved by executing this command in the command line: `git config --config lfs.largefilewarning false`. 

Since users do not utilize a CLI in the ARC Manager, these configurations need to be made during the backend phase.

**Comment by Lu98Be** [comment]
added working git lfs in #5
